export const USER_POST_FETCH_REQUEST = 'USER_POST_FETCH_REQUEST'
export const USER_POST_FETCH_SUCCEEDED = 'USER_POST_FETCH_SUCCEEDED'
export const USER_POST_FETCH_FAILED= 'USER_POST_FETCH_FAILED'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT = 'LOGOUT'
export const STOP_LOGIN_PENDING = 'STOP_LOGIN_PENDING'